# Generated by Django 3.1.1 on 2021-04-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVeterinarios', '0002_alter_veterinario_horario_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
