# Generated by Django 3.2 on 2021-04-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVeterinarios', '0003_auto_20210425_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='id_veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Veterinario', to='gestionVeterinarios.veterinario'),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='animales',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/{self.id}'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
