# Generated by Django 3.2 on 2021-04-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVeterinarios', '0004_auto_20210427_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='nombre_consulta',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='pronombre',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Dra.', 'Dra.')], max_length=5),
        ),
    ]
