# Generated by Django 3.2 on 2021-04-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVeterinarios', '0006_alter_veterinario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Apodo',
        ),
        migrations.AddField(
            model_name='user',
            name='comuna',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
