# Generated by Django 3.2 on 2021-04-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVeterinarios', '0007_auto_20210428_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='comentario',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
    ]
