# Generated by Django 3.2 on 2021-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVeterinarios', '0008_auto_20210429_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
