# Generated by Django 3.2 on 2021-04-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVeterinarios', '0009_alter_veterinario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comuna',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, default='I', max_length=80),
        ),
    ]
