# Generated by Django 3.2 on 2021-06-09 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVeterinarios', '0011_auto_20210609_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='veterinario',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionVeterinarios.veterinario'),
        ),
    ]
